services:
  mcp-server:
    build: .
    container_name: my-first-mcp
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - CHROMA_URL=http://chroma:8000
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mcp-network
  chroma:
    image: chromadb/chroma:0.5.18
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_ENABLE_REST=true
#      - CHROMA_SERVER_API_VERSION=v1
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 