services:
  mcp-server:
    build: .
    container_name: my-first-mcp
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 